apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: conversor-cert
  namespace: default
spec:
  secretName: conversor-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: devops20251-conversorpdf.duckdns.org
  dnsNames:
    - devops20251-conversorpdf.duckdns.org
  usages:
    - digital signature
    - key encipherment
    - server auth
